CREATE TABLE TB_TEXT(
	TEXT_NO NUMBER(5) NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	USER_ID VARCHAR2(16),
	REG_TIME DATE NOT NULL,
	READ_COUNT NUMBER(5) NOT NULL,
	RECOM_COUNT NUMBER(5) NOT NULL
);

CREATE TABLE TB_USER(
	USER_ID VARCHAR2(16) NOT NULL,
	PASSWORD VARCHAR2(16) NOT NULL,
	EMAIL VARCHAR2(60)
);

CREATE TABLE TB_READ_RECOM(
	TEXT_NO NUMBER(5) NOT NULL,
	USER_ID VARCHAR2(16) NOT NULL,
	THE_TIME DATE NOT NULL
);

INSERT INTO TB_USER(USER_ID, PASSWORD, EMAIL)
VALUES('root', 'abcd1234','root@noname.com');
INSERT INTO TB_USER(USER_ID, PASSWORD, EMAIL)
VALUES('user1', 'abcd1234','user1@noname.com');
INSERT INTO TB_USER(USER_ID, PASSWORD)
VALUES('user2', 'abcd1234');
INSERT INTO TB_USER(USER_ID, PASSWORD)
VALUES('user3', 'abcd1234');

UPDATE TB_USER
SET PASSWORD = '12341234'
WHERE USER_ID = 'user1';

UPDATE TB_USER
SET EMAIL = 'user3@noname.com'
WHERE USER_ID = 'user3';



SELECT * FROM TB_USER;

INSERT INTO TB_TEXT
VALUES (1, '오늘하루', '할 일 없었다','user1', SYSDATE, 0, 0 );
INSERT INTO TB_TEXT
VALUES (2, '오늘하루', '할 일 많았다','user2', SYSDATE, 0, 0 );
INSERT INTO TB_TEXT
VALUES (3, '오늘하루', '할 일이란 과연 무엇일까?','user3', SYSDATE, 0, 0 );
COMMIT;

SELECT * FROM TB_TEXT;

UPDATE TB_TEXT
SET READ_COUNT = 0;
UPDATE TB_TEXT
SET RECOM_COUNT = 0;

-- user3
UPDATE TB_TEXT
SET READ_COUNT = READ_COUNT + 1
WHERE USER_ID <> 'user1' AND TEXT_NO = 1 and (select count(*) from TB_READ_RECOM user_id = 'user_3' and text_no = 1) < 1;

select * from TB_TEXT;
TB_READ_RECOM

UPDATE TB_TEXT
SET RECOM_COUNT = RECOM_COUNT + 1
WHERE (
	SELECT USER_ID FROM TB_TEXT
	WHERE TEXT_NO = 1) != 'user2' AND TEXT_NO = 1;

UPDATE TB_TEXT
SET RECOM_COUNT = RECOM_COUNT + 1
WHERE (
	SELECT USER_ID FROM TB_TEXT
	WHERE TEXT_NO = 1) != 'user3' AND TEXT_NO = 1;
