--1
SELECT NAME, TITLE, SALARY, DEPT_ID FROM S_EMP
WHERE DEPT_ID IN (112, 118) AND SALARY BETWEEN 1500 AND 4000;

--2
SELECT NAME, TITLE, SALARY FROM S_EMP
WHERE MANAGER_ID IS NULL;

--3
SELECT NAME, TITLE, SALARY FROM S_EMP
WHERE TITLE LIKE '%부장' AND SALARY >= 3000;

--4
SELECT NAME, TITLE, SALARY FROM S_EMP
WHERE (TITLE LIKE '%부장' OR TITLE LIKE '%과장') 
	AND DEPT_ID IN (112, 113, 117, 118) AND SALARY BETWEEN 2300 AND 3000;
	
--5
SELECT NAME, TITLE, SALARY, START_DATE FROM S_EMP
WHERE (TITLE LIKE '%부장' OR TITLE LIKE '%과장') 
	AND TO_CHAR(START_DATE,'MM') = '03';

SELECT * FROM S_EMP;

--6
SELECT NAME, SALARY *16 + 1000 AS SALARY FROM S_EMP;

--7
SELECT NAME || ' ' || TITLE || '의  급여 ' || SALARY AS "직원 급여"
FROM S_EMP;

--8
SELECT * FROM S_EMP
WHERE COMMISSION_PCT IS NOT NULL AND MANAGER_ID IS NOT NULL AND SALARY >= 2500;
