--1.
SELECT * FROM S_EMP;
SELECT DEPT_ID, MIN(SALARY)
  FROM S_EMP
  GROUP BY DEPT_ID;
  
--2.
SELECT TITLE, MIN(SALARY)
  FROM S_EMP
  GROUP BY TITLE
  HAVING TITLE NOT LIKE '%부장';
  
--3.
SELECT TITLE, AVG(SALARY)
  FROM S_EMP
  GROUP BY TITLE;

--4.
SELECT TITLE, COUNT(*) AS "인원수"
  FROM S_EMP
  GROUP BY TITLE;
  
--5.
SELECT TITLE, MAX(SALARY)
  FROM S_EMP
  GROUP BY TITLE
  HAVING MAX(SALARY) >= 2000;
  
--6.
SELECT TITLE, MIN(SALARY) AS SAL
  FROM S_EMP
  GROUP BY TITLE
  HAVING TITLE NOT LIKE '%부장'
  ORDER BY SAL DESC;

--7.
SELECT TITLE, AVG(SALARY) AS AVG_SAL
  FROM S_EMP
  GROUP BY TITLE
  HAVING TITLE <> '사원'
  ORDER BY AVG_SAL;
  
--8.
SELECT TITLE, SUM(SALARY) AS TOT_SAL
  FROM S_EMP
  GROUP BY TITLE
  HAVING TITLE <> '사원' AND SUM(SALARY) >= 2000
  ORDER BY TOT_SAL DESC;
  
--9.
SELECT UPPER(SUBSTR(MAILID, 1, 1)) || LOWER(SUBSTR(MAILID, 2)) AS MAILID
  FROM S_EMP;
  
--10.
SELECT NAME
  FROM S_EMP
  WHERE LENGTH(NAME) > 2;

--11.
SELECT SALARY * TRUNC(MONTHS_BETWEEN(SYSDATE, START_DATE)) AS SAL, NAME
 FROM S_EMP;

--12.
SELECT NAME, NVL(TO_CHAR(COMMISSION_PCT), '커미션 없음') AS COMMISSION
  FROM S_EMP;
  
--13.
SELECT NAME, 
	   CASE WHEN TITLE = '사원' THEN TRUNC(SALARY + SALARY * 0.1)
	        WHEN TITLE = '과장' THEN TRUNC(SALARY + SALARY * 0.2)
	   ELSE TRUNC(SALARY + SALARY * 0.1)
	   END AS SAL
  FROM S_EMP;
  
--14.
SELECT NAME, SALARY, REPLACE(LPAD(' ', FLOOR(SALARY/100), '*'),' ', '*' )AS SAL
  FROM S_EMP;